package com.github.damianszwed.fishky.proxy.component;

interface OutputSamples {

  String FLASHCARD_FOLDERS = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tZGVmYXVsdA==\",\n"
      + "    \"name\": \"Default\",\n"
      + "    \"owner\": \"user1@example.com\",\n"
      + "    \"flashcards\": [\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "        \"question\": \"questionA\",\n"
      + "        \"answers\": [\"answerA\"]\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25i\",\n"
      + "        \"question\": \"questionB\",\n"
      + "        \"answers\": [\"answerB\"]\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "        \"question\": \"questionC\",\n"
      + "        \"answers\": [\"answerC\"]\n"
      + "      }\n"
      + "    ]\n"
      + "  }\n"
      + "]";

  String FLASHCARD_FOLDERS_WITH_NEW_FLASHCARD = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tZGVmYXVsdA==\",\n"
      + "    \"name\": \"Default\",\n"
      + "    \"owner\": \"user1@example.com\",\n"
      + "    \"flashcards\": [\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "        \"question\": \"questionA\",\n"
      + "        \"answers\": [\"answerA\"]\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25i\",\n"
      + "        \"question\": \"questionB\",\n"
      + "        \"answers\": [\"answerB\"]\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "        \"question\": \"questionC\",\n"
      + "        \"answers\": [\"answerC\"]\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25k\",\n"
      + "        \"question\": \"questionD\",\n"
      + "        \"answers\": [\"answerD\"]\n"
      + "      }\n"
      + "    ]\n"
      + "  }\n"
      + "]";

  String FLASHCARD_FOLDERS_WITHOUT_ONE_FLASHCARD = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tZGVmYXVsdA==\",\n"
      + "    \"name\": \"Default\",\n"
      + "    \"owner\": \"user1@example.com\",\n"
      + "    \"flashcards\": [\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "        \"question\": \"questionA\",\n"
      + "        \"answers\": [\"answerA\"]\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "        \"question\": \"questionC\",\n"
      + "        \"answers\": [\"answerC\"]\n"
      + "      }\n"
      + "    ]\n"
      + "  }\n"
      + "]";
  String FLASHCARD_FOLDERS_WITH_ONE_FLASHCARD_MODIFIED = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tZGVmYXVsdA==\",\n"
      + "    \"name\": \"Default\",\n"
      + "    \"owner\": \"user1@example.com\",\n"
      + "    \"flashcards\": [\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "        \"question\": \"questionA\",\n"
      + "        \"answers\": [\"answerA\"]\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25i\",\n"
      + "        \"question\": \"questionDD\",\n"
      + "        \"answers\": [\"answerDD\"]\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "        \"question\": \"questionC\",\n"
      + "        \"answers\": [\"answerC\"]\n"
      + "      }\n"
      + "    ]\n"
      + "  }\n"
      + "]";
  ;
}
