package com.github.damianszwed.fishky.proxy.component;

interface OutputSamples {

  String FLASHCARD_FOLDERS = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tZGVmYXVsdA==\",\n"
      + "    \"name\": \"Default\",\n"
      + "    \"owner\": \"user1@example.com\",\n"
      + "    \"flashcards\": [\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "        \"question\": \"questionA\",\n"
      + "        \"answer\": \"answerA\"\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25i\",\n"
      + "        \"question\": \"questionB\",\n"
      + "        \"answer\": \"answerB\"\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "        \"question\": \"questionC\",\n"
      + "        \"answer\": \"answerC\"\n"
      + "      }\n"
      + "    ]\n"
      + "  }\n"
      + "]";

  String FLASHCARD_FOLDERS_WITH_NEW_FLASHCARD = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tZGVmYXVsdA==\",\n"
      + "    \"name\": \"Default\",\n"
      + "    \"owner\": \"user1@example.com\",\n"
      + "    \"flashcards\": [\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "        \"question\": \"questionA\",\n"
      + "        \"answer\": \"answerA\"\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25i\",\n"
      + "        \"question\": \"questionB\",\n"
      + "        \"answer\": \"answerB\"\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "        \"question\": \"questionC\",\n"
      + "        \"answer\": \"answerC\"\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25k\",\n"
      + "        \"question\": \"questionD\",\n"
      + "        \"answer\": \"answerD\"\n"
      + "      }\n"
      + "    ]\n"
      + "  }\n"
      + "]";

  String FLASHCARD_FOLDERS_WITHOUT_ONE_FLASHCARD = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tZGVmYXVsdA==\",\n"
      + "    \"name\": \"Default\",\n"
      + "    \"owner\": \"user1@example.com\",\n"
      + "    \"flashcards\": [\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "        \"question\": \"questionA\",\n"
      + "        \"answer\": \"answerA\"\n"
      + "      },\n"
      + "      {\n"
      + "        \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "        \"question\": \"questionC\",\n"
      + "        \"answer\": \"answerC\"\n"
      + "      }\n"
      + "    ]\n"
      + "  }\n"
      + "]";

  String DEFAULT_FLASHCARDS_ARRAY = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "    \"question\": \"questionA\",\n"
      + "    \"answer\": \"answerA\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25i\",\n"
      + "    \"question\": \"questionB\",\n"
      + "    \"answer\": \"answerB\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "    \"question\": \"questionC\",\n"
      + "    \"answer\": \"answerC\"\n"
      + "  }\n"
      + "]\n";

  String FLASHCARDS_ARRAY_WITH_NEW_FLASHCARD = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "    \"question\": \"questionA\",\n"
      + "    \"answer\": \"answerA\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25i\",\n"
      + "    \"question\": \"questionB\",\n"
      + "    \"answer\": \"answerB\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "    \"question\": \"questionC\",\n"
      + "    \"answer\": \"answerC\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25k\",\n"
      + "    \"question\": \"questionD\",\n"
      + "    \"answer\": \"answerD\"\n"
      + "  }\n"
      + "]\n";
  String FLASHCARDS_ARRAY_WITHOUT_ONE_FLASHCARD = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "    \"question\": \"questionA\",\n"
      + "    \"answer\": \"answerA\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "    \"question\": \"questionC\",\n"
      + "    \"answer\": \"answerC\"\n"
      + "  }\n"
      + "]\n";
}
