package com.github.damianszwed.fishky.proxy.component;

interface OutputSamples {

  String DEFAULT_FLASHCARDS_ARRAY = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "    \"question\": \"questionA\",\n"
      + "    \"answer\": \"answerA\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25i\",\n"
      + "    \"question\": \"questionB\",\n"
      + "    \"answer\": \"answerB\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "    \"question\": \"questionC\",\n"
      + "    \"answer\": \"answerC\"\n"
      + "  }\n"
      + "]\n";

  String FLASHCARDS_ARRAY_WITH_NEW_FLASHCARD = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "    \"question\": \"questionA\",\n"
      + "    \"answer\": \"answerA\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25i\",\n"
      + "    \"question\": \"questionB\",\n"
      + "    \"answer\": \"answerB\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "    \"question\": \"questionC\",\n"
      + "    \"answer\": \"answerC\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25k\",\n"
      + "    \"question\": \"questionD\",\n"
      + "    \"answer\": \"answerD\"\n"
      + "  }\n"
      + "]\n";
  String FLASHCARDS_ARRAY_WITHOUT_ONE_FLASHCARD = "[\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25h\",\n"
      + "    \"question\": \"questionA\",\n"
      + "    \"answer\": \"answerA\"\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"dXNlcjFAZXhhbXBsZS5jb20tcXVlc3Rpb25j\",\n"
      + "    \"question\": \"questionC\",\n"
      + "    \"answer\": \"answerC\"\n"
      + "  }\n"
      + "]\n";
}
