apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: fishky-proxy-backend-config
spec:
  #This config has to be applied so GCP will not interrupt SSE connections.
  timeoutSec: 215999
  sessionAffinity:
    affinityType: "CLIENT_IP"