apiVersion: v1
kind: Service
metadata:
  name: fishky-proxy-endpoint
  labels:
    app: fishky-proxy
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 30508
    nodePort: 30508
  selector:
    app: fishky-proxy
    tier: backend
