apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishky-flashcard-service
spec:
  selector:
    matchLabels:
      app: fishky-flashcard-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: fishky-flashcard-service
        tier: backend
    spec:
      containers:
      - name: fishky-flashcard-service
        image: damianiero/fishky-flashcard-service:1.0.1
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: MONGODB-URI
          valueFrom:
            secretKeyRef:
              name: fishky-mongo-secret
              key: mongodb.uri
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: fishky-flashcard-service-secret
            mountPath: "/app/application.yml"
            readOnly: true
            subPath: application.yml
        readinessProbe:
          httpGet:
            path: /healthCheck
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /healthCheck
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 3
          periodSeconds: 15
          failureThreshold: 4
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "320m"
      volumes:
        - name: fishky-flashcard-service-secret
          secret:
            secretName: fishky-flashcard-service-secret