apiVersion: v1
kind: Service
metadata:
  name: fishky-flashcard-service
  labels:
    app: fishky-flashcard-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 30508
    protocol: TCP
    targetPort: 8080
  selector:
    app: fishky-flashcard-service
    tier: backend
