apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fishky-proxy-ingress
  annotations:
    #gcloud compute addresses create api-fishky-pl --global
    #gcloud compute addresses describe api-fishky-pl --global
    kubernetes.io/ingress.global-static-ip-name: api-fishky-pl
    networking.gke.io/managed-certificates: fishky-managed-certificate
spec:
  backend:
    serviceName: fishky-proxy-service
    servicePort: 30508