apiVersion: v1
kind: Service
metadata:
  name: fishky-proxy-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"30508":"fishky-proxy-backend-config"}}'
  labels:
    app: fishky-proxy
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 30508
    protocol: TCP
    targetPort: 8080
  selector:
    app: fishky-proxy
    tier: backend
