apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fishky-flashcard-service-ingress
  annotations:
    #gcloud compute addresses create api-fishky-pl --global
    #gcloud compute addresses describe api-fishky-pl --global
    kubernetes.io/ingress.global-static-ip-name: api-fishky-pl
    networking.gke.io/managed-certificates: fishky-managed-certificate
    kubernetes.io/ingress.class: "gce"
spec:
#  ingressClassName: "gce" # TODO this will replace kubernetes.io/ingress.class: "gce"
  defaultBackend:
    service:
      name: fishky-flashcard-service
      port:
        number: 30508