server:
  port: 30508

logging:
  level:
    org.mongodb: INFO
    org.springframework: INFO
    ROOT: INFO

spring:
  application:
    name: fishky-proxy
  profiles:
    active: development
  data:
    mongodb:
      uri: ${MONGODB-URI}