logging:
  level:
    org.mongodb: INFO

spring:
  data:
    mongodb:
      uri: ${MONGODB-URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-289513.oktapreview.com/oauth2/default
          #TODO(Damian.Szwed)issuer-uri should be configurable
fishky:
  system-user-lower-cased-internal-id: 0oa12bd4uceb7edps0h8
