logging:
  level:
    org.mongodb: INFO

spring:
  data:
    mongodb:
      uri: ${MONGODB-URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.fishky.pl/oauth2/default
fishky:
  system-user-lower-cased-internal-id: 0oa12bd4uceb7edps0h8
