server:
  port: 30508

spring:
  application:
    name: fishky-proxy
  profiles:
    active: development
  data:
    mongodb:
      uri: mongodb+srv://fishky-db:<PASSWORD>@cluster168-h7du4.gcp.mongodb.net/test?retryWrites=true
      database: test